(function(){
'use strict';
var S={titles:[],home:{heroTitleIds:[],shelves:[]},revision:'',screen:'splash',title:null,ep:null,tracks:{audio:[],subtitles:[]},qualities:[],modal:false,controls:true,timer:null,toast:null,save:null,lastFocus:null};
var E={},P;
function $(x){return document.getElementById(x);}function esc(x){return String(x==null?'':x).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function cache(){var a=['splash','splash-message','home-screen','home-content','catalog-status','detail-screen','detail-backdrop','detail-content','player-screen','player-controls','player-title','player-subtitle-title','player-badge','timeline-progress','time-current','time-duration','buffering','buffering-text','subtitle-layer','modal','modal-title','modal-list','toast'];for(var i=0;i<a.length;i++)E[a[i]]=$(a[i]);}
function screen(n){var a=['splash','home','detail','player'],id={splash:'splash',home:'home-screen',detail:'detail-screen',player:'player-screen'};for(var i=0;i<a.length;i++)E[id[a[i]]].classList.toggle('active',a[i]===n);S.screen=n;closeModal();if(n!=='player')clearCtl();}
function toast(m,t){E.toast.textContent=m;E.toast.classList.remove('hidden');clearTimeout(S.toast);S.toast=setTimeout(function(){E.toast.classList.add('hidden');},t||2600);}
function store(k,v){try{localStorage.setItem('film2.tv.'+k,JSON.stringify(v));}catch(e){}}function load(k,d){try{var v=localStorage.getItem('film2.tv.'+k);return v?JSON.parse(v):d;}catch(e){return d;}}
function mediaKey(m){return m.titleId+(m.season!=null?'.s'+m.season+'.e'+m.episode:'.movie');}
function progress(m){return load('progress.'+mediaKey(m),{position:0,duration:0,finished:false});}
function saveProgress(force){if(!P||!P.media)return;clearTimeout(S.save);var run=function(){var d=P.duration||0,n=P.now||0;store('progress.'+mediaKey(P.media),{position:n,duration:d,finished:d>0&&n/d>.95,updatedAt:Date.now()});};if(force)run();else S.save=setTimeout(run,500);}
function pref(m,k){return load('pref.'+mediaKey(m)+'.'+k,null);}function savePref(m,k,v){store('pref.'+mediaKey(m)+'.'+k,v);}
function byId(id){for(var i=0;i<S.titles.length;i++)if(S.titles[i].id===id)return S.titles[i];return null;}
function playable(t){if(t.type==='movie')return t.asset&&(t.asset.videoUrl||t.asset.masterPlaylistUrl);for(var s=0;s<t.seasons.length;s++)for(var e=0;e<t.seasons[s].episodes.length;e++){var x=t.seasons[s].episodes[e];if(x.status==='ready'&&x.asset&&(x.asset.videoUrl||x.asset.masterPlaylistUrl))return true;}return false;}
function firstMedia(t){if(t.type==='movie')return {titleId:t.id,title:t.title,subtitle:'',asset:t.asset,poster:t.posterUrl,backdrop:t.backdropUrl};for(var s=0;s<t.seasons.length;s++)for(var e=0;e<t.seasons[s].episodes.length;e++){var x=t.seasons[s].episodes[e];if(x.status==='ready'&&x.asset&&(x.asset.videoUrl||x.asset.masterPlaylistUrl))return {titleId:t.id,title:t.title,subtitle:'S'+t.seasons[s].seasonNumber+' B'+x.episodeNumber+' • '+x.title,season:t.seasons[s].seasonNumber,episode:x.episodeNumber,asset:x.asset,poster:x.stillUrl||t.posterUrl,backdrop:x.stillUrl||t.backdropUrl};}return null;}
function heroHtml(t){if(!t)return '<div class="empty-state">Henüz oynatılabilir içerik yok.</div>';var m=(t.releaseYear?esc(t.releaseYear)+' &nbsp; • &nbsp; ':'')+esc((t.genres||[]).slice(0,3).join(' • '));return '<div class="hero" style="background-image:url(\''+esc(t.backdropUrl||t.posterUrl||'')+'\')"><div class="hero-copy">'+(t.logoUrl?'<img class="hero-logo" src="'+esc(t.logoUrl)+'">':'<h1 class="hero-title">'+esc(t.title)+'</h1>')+'<div class="hero-meta">'+m+'</div><div class="hero-overview">'+esc(t.overview||'')+'</div><div class="hero-actions"><button class="focusable hero-button primary" data-open="'+esc(t.id)+'">İzle</button><button class="focusable hero-button" data-detail="'+esc(t.id)+'">Ayrıntılar</button></div></div></div>';}
function card(t){var p=progress(firstMedia(t)||{titleId:t.id}),pct=p.duration?Math.max(0,Math.min(100,p.position/p.duration*100)):0;return '<button class="focusable card" data-detail="'+esc(t.id)+'">'+(t.posterUrl?'<img src="'+esc(t.posterUrl)+'" alt="">':'<div class="card-fallback">'+esc(t.title)+'</div>')+'<div class="card-shade"></div><div class="card-title">'+esc(t.title)+'</div>'+(pct>1&&pct<95?'<div class="progress-strip" style="width:'+pct+'%"></div>':'')+'</button>';}
function shelf(title,items){if(!items.length)return '';var h='<section class="shelf"><h2 class="shelf-title">'+esc(title)+'</h2><div class="shelf-row">';for(var i=0;i<items.length;i++)h+=card(items[i]);return h+'</div></section>';}
function renderHome(){var hero=null,ids=S.home.heroTitleIds||[];for(var i=0;i<ids.length&&!hero;i++)hero=byId(ids[i]);if(!hero)hero=S.titles[0]||null;var used={},shelves='',resume=[];for(i=0;i<S.titles.length;i++){var fm=firstMedia(S.titles[i]),pr=fm?progress(fm):null;if(pr&&pr.position>60000&&!pr.finished)resume.push(S.titles[i]);}if(resume.length)shelves+=shelf('İzlemeye Devam Et',resume);
var hs=S.home.shelves||[];for(i=0;i<hs.length;i++){var sh=hs[i];if(sh.enabled===false)continue;var arr=[];for(var j=0;j<(sh.titleIds||[]).length;j++){var t=byId(sh.titleIds[j]);if(t&&playable(t)){arr.push(t);used[t.id]=1;}}if(sh.shuffle)arr.sort(function(){return Math.random()-.5;});if(sh.maxItems)arr=arr.slice(0,sh.maxItems);shelves+=shelf(sh.title||'Seçkiler',arr);}var all=[];for(i=0;i<S.titles.length;i++)if(!used[S.titles[i].id])all.push(S.titles[i]);if(all.length)shelves+=shelf('Tüm İçerikler',all);E['home-content'].innerHTML=heroHtml(hero)+'<div class="shelves">'+shelves+'</div>';bindClicks(E['home-content']);screen('home');setTimeout(function(){focusFirst();},40);}
function detail(id){var t=byId(id);if(!t)return;S.title=t;E['detail-backdrop'].style.backgroundImage=t.backdropUrl?'url("'+String(t.backdropUrl).replace(/"/g,'')+'")':'';var h='<div class="detail-main">'+(t.logoUrl?'<img class="detail-logo" src="'+esc(t.logoUrl)+'">':'<h1 class="detail-title">'+esc(t.title)+'</h1>')+'<div class="detail-meta">'+(t.releaseYear?'<span>'+esc(t.releaseYear)+'</span>':'')+'<span>'+esc((t.genres||[]).join(' • '))+'</span></div><div class="detail-overview">'+esc(t.overview||'')+'</div><div class="detail-actions"><button class="focusable detail-button primary" data-play-first="'+esc(t.id)+'">'+(progress(firstMedia(t)||{titleId:t.id}).position>60000?'Devam Et':'Oynat')+'</button><button class="focusable detail-button" data-back-home="1">Geri</button></div></div>';
if(t.type==='series'){for(var s=0;s<t.seasons.length;s++){var sn=t.seasons[s],eps='';for(var e=0;e<sn.episodes.length;e++){var x=sn.episodes[e];if(x.status!=='ready'||!x.asset||!(x.asset.videoUrl||x.asset.masterPlaylistUrl))continue;eps+='<button class="focusable episode-card" data-episode="'+s+':'+e+'"><div class="ep-no">Bölüm '+esc(x.episodeNumber)+'</div><div class="ep-title">'+esc(x.title)+'</div><div class="ep-overview">'+esc(x.overview||'')+'</div></button>';}if(eps)h+='<section class="detail-section"><h2>'+esc(sn.name||('Sezon '+sn.seasonNumber))+'</h2><div class="episode-list">'+eps+'</div></section>';}}
E['detail-content'].innerHTML=h;bindClicks(E['detail-content']);screen('detail');setTimeout(focusFirst,30);}
function episodeMedia(t,si,ei){var sn=t.seasons[si],x=sn&&sn.episodes[ei];if(!x)return null;return {titleId:t.id,title:t.title,subtitle:'S'+sn.seasonNumber+' B'+x.episodeNumber+' • '+x.title,season:sn.seasonNumber,episode:x.episodeNumber,asset:x.asset,poster:x.stillUrl||t.posterUrl,backdrop:x.stillUrl||t.backdropUrl};}
function qualityList(a){var q=[],v=a.videoVariants||[];if(a.videoUrl)q.push({label:'Kaynak',url:a.videoUrl,source:true});for(var i=0;i<v.length;i++)if(v[i].url)q.push(v[i]);if(!q.length&&a.masterPlaylistUrl)q.push({label:'Otomatik',url:a.masterPlaylistUrl,source:true});var seen={},out=[];for(i=0;i<q.length;i++)if(!seen[q[i].url]){seen[q[i].url]=1;out.push(q[i]);}return out;}
function start(m){if(!m||!m.asset)return;S.ep=m;S.qualities=qualityList(m.asset);var pr=progress(m),start=pr.finished?0:(pr.position||0),qp=pref(m,'quality'),url=null;for(var i=0;i<S.qualities.length;i++)if(qp&&S.qualities[i].label===qp)url=S.qualities[i].url;if(!url)url=(S.qualities[0]&&S.qualities[0].url)||m.asset.videoUrl||m.asset.masterPlaylistUrl;E['player-title'].textContent=m.title;E['player-subtitle-title'].textContent=m.subtitle||'';E['player-badge'].textContent=(S.qualities[0]&&S.qualities[0].label)||'';E['time-current'].textContent='00:00';E['time-duration'].textContent=Film2TVPlayer.formatTime((m.asset.durationSeconds||0)*1000);E['timeline-progress'].style.width='0%';screen('player');showCtl();P.open(m,{url:url,start:start,autoplay:true});setTimeout(function(){focusAction('toggle-play');},180);}
function initPlayer(){P=new Film2TVPlayer({buffer:function(on,p){E.buffering.classList.toggle('hidden',!on);E['buffering-text'].textContent='Yükleniyor'+(p?' %'+p:'')+'…';},time:function(n,d){E['time-current'].textContent=Film2TVPlayer.formatTime(n);E['time-duration'].textContent=Film2TVPlayer.formatTime(d);E['timeline-progress'].style.width=(d?Math.min(100,n/d*100):0)+'%';saveProgress(false);},state:function(st){var b=document.querySelector('[data-action="toggle-play"]');if(b)b.textContent=st==='playing'?'Duraklat':'Oynat';},subtitle:function(t){E['subtitle-layer'].textContent=t||'';},tracks:function(t){S.tracks=t||{audio:[],subtitles:[]};restorePrefs();},completed:function(){saveProgress(true);toast('Oynatma tamamlandı.');},error:function(m){E.buffering.classList.add('hidden');toast(m,5000);}});}
function restorePrefs(){if(!S.ep)return;var a=pref(S.ep,'audio'),s=pref(S.ep,'subtitle');if(a&&S.tracks.audio.length){for(var i=0;i<S.tracks.audio.length;i++)if((S.tracks.audio[i].language||'')===a.language&&S.tracks.audio[i].type===a.type){P.selectAudio(S.tracks.audio[i],true);break;}}if(s&&S.tracks.subtitles.length){for(i=0;i<S.tracks.subtitles.length;i++)if((S.tracks.subtitles[i].language||'')===s.language&&S.tracks.subtitles[i].type===s.type){P.selectSub(S.tracks.subtitles[i],true);break;}}}
function ctl(a){showCtl();if(a==='toggle-play')P.toggle();else if(a==='rewind')P.seekBy(-10000);else if(a==='forward')P.seekBy(10000);else if(a==='audio')openTracks('audio');else if(a==='subtitles')openTracks('subtitles');else if(a==='quality')openQuality();else if(a==='back')leavePlayer();}
function leavePlayer(){saveProgress(true);P.destroy();E['subtitle-layer'].textContent='';E.buffering.classList.add('hidden');if(S.title)detail(S.title.id);else renderHome();}
function showCtl(){S.controls=true;E['player-controls'].classList.add('visible');clearCtl();S.timer=setTimeout(function(){if(S.screen==='player'&&!S.modal){E['player-controls'].classList.remove('visible');S.controls=false;}},5500);}function clearCtl(){clearTimeout(S.timer);S.timer=null;}
function openTracks(kind){var a=kind==='audio'?S.tracks.audio:S.tracks.subtitles,title=kind==='audio'?'Ses':'Altyazı';openModal(title,a,function(x){if(kind==='audio'){P.selectAudio(x);savePref(S.ep,'audio',{type:x.type,language:x.language,url:x.url||null});}else{P.selectSub(x);savePref(S.ep,'subtitle',{type:x.type,language:x.language,url:x.url||null});}});}
function openQuality(){openModal('Kalite',S.qualities,function(x){E['player-badge'].textContent=x.label||'';savePref(S.ep,'quality',x.label||'');P.changeSource(x.url);});}
function openModal(title,opts,fn){S.modal=true;S.modalFn=fn;S.modalOpts=opts||[];E['modal-title'].textContent=title;var h='';for(var i=0;i<S.modalOpts.length;i++){var x=S.modalOpts[i];h+='<button class="focusable modal-option" data-modal="'+i+'"><div class="option-title">'+esc(x.label||x.language||('Seçenek '+(i+1)))+'</div><div class="option-meta">'+esc(x.meta||(x.height?x.height+'p':''))+'</div></button>';}if(!h)h='<div style="padding:25px;color:#aaa">Seçenek bulunamadı.</div>';E['modal-list'].innerHTML=h;E.modal.classList.remove('hidden');bindClicks(E['modal-list']);setTimeout(function(){var b=E['modal-list'].querySelector('.focusable');if(b)focus(b);},20);}
function closeModal(){if(!S.modal)return;S.modal=false;E.modal.classList.add('hidden');E['modal-list'].innerHTML='';if(S.screen==='player')setTimeout(function(){focusAction('toggle-play');},10);}
function bindClicks(root){root.onclick=function(ev){var n=ev.target;while(n&&n!==root&&!n.getAttribute('data-detail')&&!n.getAttribute('data-open')&&!n.getAttribute('data-play-first')&&!n.getAttribute('data-episode')&&!n.getAttribute('data-action')&&!n.getAttribute('data-modal')&&!n.getAttribute('data-back-home'))n=n.parentNode;if(!n||n===root)return;if(n.getAttribute('data-detail'))detail(n.getAttribute('data-detail'));else if(n.getAttribute('data-open')){var t=byId(n.getAttribute('data-open'));S.title=t;start(firstMedia(t));}else if(n.getAttribute('data-play-first')){var t2=byId(n.getAttribute('data-play-first'));S.title=t2;start(firstMedia(t2));}else if(n.getAttribute('data-episode')){var z=n.getAttribute('data-episode').split(':');start(episodeMedia(S.title,+z[0],+z[1]));}else if(n.getAttribute('data-action'))ctl(n.getAttribute('data-action'));else if(n.getAttribute('data-modal')!=null){var x=S.modalOpts[+n.getAttribute('data-modal')];if(x&&S.modalFn)S.modalFn(x);closeModal();}else if(n.getAttribute('data-back-home'))renderHome();};}
function focus(el){if(!el)return;var old=document.querySelector('.focusable.focused');if(old)old.classList.remove('focused');el.classList.add('focused');try{el.focus();}catch(e){}try{el.scrollIntoView({block:'nearest',inline:'nearest'});}catch(e2){try{el.scrollIntoView(false);}catch(e3){}}S.lastFocus=el;}
function visible(){var a=document.querySelectorAll('.screen.active .focusable'),o=[];for(var i=0;i<a.length;i++)if(a[i].offsetWidth||a[i].offsetHeight)o.push(a[i]);return o;}function focusFirst(){var a=visible();if(a.length)focus(a[0]);}
function focusAction(a){var b=document.querySelector('[data-action="'+a+'"]');if(b)focus(b);}
function move(dir){var a=visible(),cur=document.activeElement;if(!cur||a.indexOf(cur)<0){focusFirst();return;}var r=cur.getBoundingClientRect(),cx=(r.left+r.right)/2,cy=(r.top+r.bottom)/2,best=null,score=1e9;for(var i=0;i<a.length;i++){var x=a[i];if(x===cur)continue;var q=x.getBoundingClientRect(),xx=(q.left+q.right)/2,yy=(q.top+q.bottom)/2,dx=xx-cx,dy=yy-cy;if((dir==='left'&&dx>=-4)||(dir==='right'&&dx<=4)||(dir==='up'&&dy>=-4)||(dir==='down'&&dy<=4))continue;var primary=(dir==='left'||dir==='right')?Math.abs(dx):Math.abs(dy),cross=(dir==='left'||dir==='right')?Math.abs(dy):Math.abs(dx),sc=primary+cross*2.2;if(sc<score){score=sc;best=x;}}if(best)focus(best);}
function back(){if(S.modal){closeModal();return;}if(S.screen==='player'){leavePlayer();return;}if(S.screen==='detail'){renderHome();return;}if(S.screen==='home'){try{tizen.application.getCurrentApplication().exit();}catch(e){window.close();}}}
function key(e){var c=e.keyCode;if(c===37){if(S.screen==='player'&&!S.modal&&(!S.controls||document.activeElement===document.body)){showCtl();P.seekBy(-10000);}else move('left');e.preventDefault();}else if(c===39){if(S.screen==='player'&&!S.modal&&(!S.controls||document.activeElement===document.body)){showCtl();P.seekBy(10000);}else move('right');e.preventDefault();}else if(c===38){if(S.screen==='player')showCtl();move('up');e.preventDefault();}else if(c===40){if(S.screen==='player')showCtl();move('down');e.preventDefault();}else if(c===13){var f=document.activeElement;if(f&&f.click)f.click();e.preventDefault();}else if(c===10009||c===27){back();e.preventDefault();}else if(c===415){if(S.screen==='player'&&!P.playing)P.toggle();}else if(c===19){if(S.screen==='player'&&P.playing)P.toggle();}else if(c===412){if(S.screen==='player')P.seekBy(-10000);}else if(c===417){if(S.screen==='player')P.seekBy(10000);}else if(c===413){if(S.screen==='player')leavePlayer();}}
function keys(){try{var names=['MediaPlay','MediaPause','MediaPlayPause','MediaRewind','MediaFastForward','MediaStop'];for(var i=0;i<names.length;i++)try{tizen.tvinputdevice.registerKey(names[i]);}catch(e){}}catch(x){}document.addEventListener('keydown',key,false);}
function loadAll(){E['splash-message'].textContent='Katalog yükleniyor…';return Promise.all([Film2Catalog.loadTitles(),Film2Catalog.loadHome(),Film2Catalog.loadRevision()]).then(function(r){S.titles=r[0];S.home=r[1]||{heroTitleIds:[],shelves:[]};S.revision=r[2]||'';E['catalog-status'].textContent='Güncel';renderHome();}).catch(function(e){E['splash-message'].textContent='Katalog yüklenemedi: '+e.message;setTimeout(loadAll,5000);});}
function poll(){setInterval(function(){if(S.screen!=='home')return;Film2Catalog.loadRevision().then(function(r){if(r&&S.revision&&r!==S.revision){E['catalog-status'].textContent='Güncelleniyor…';loadAll();}else if(r)S.revision=r;});},300000);}
function visibility(){document.addEventListener('visibilitychange',function(){if(S.screen!=='player')return;if(document.hidden){saveProgress(true);P.suspend();}else P.restore();});window.addEventListener('beforeunload',function(){saveProgress(true);if(P)P.destroy();});}
function init(){cache();initPlayer();bindClicks(E['player-controls']);keys();visibility();loadAll();poll();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
}());
