(function (g) {
'use strict';
var REPO='apexlions16/film2',BRANCH='main',RAW='https://raw.githubusercontent.com/'+REPO+'/'+BRANCH+'/';
function xhrText(url){return new Promise(function(resolve,reject){var xhr=new XMLHttpRequest();xhr.open('GET',url,true);xhr.timeout=25000;try{xhr.setRequestHeader('Cache-Control','no-cache');}catch(e){}xhr.onreadystatechange=function(){if(xhr.readyState!==4)return;if(xhr.status>=200&&xhr.status<300)resolve(xhr.responseText);else reject(new Error('HTTP '+xhr.status+' — '+url));};xhr.onerror=function(){reject(new Error('Ağ hatası — '+url));};xhr.ontimeout=function(){reject(new Error('İstek zaman aşımına uğradı — '+url));};xhr.send();});}
function localText(path){return new Promise(function(resolve,reject){if(!g.tizen||!tizen.filesystem){reject(new Error('Yerel dosya sistemi kullanılamıyor.'));return;}try{var location=path.charAt(0)==='/'?'file://'+path:path;tizen.filesystem.resolve(location,function(file){try{file.openStream('r',function(stream){try{var text=stream.read(file.fileSize||10485760);stream.close();resolve(text);}catch(e){try{stream.close();}catch(x){}reject(e);}},reject,'UTF-8');}catch(e){reject(e);}},reject,'r');}catch(e){reject(e);}});}
function readText(url){var value=String(url||'');if(/^(file:\/\/|\/|downloads\/|wgt-private)/i.test(value))return localText(value.replace(/^file:\/\//i,''));return xhrText(value);}
function xhrJson(url){return xhrText(url).then(function(text){return JSON.parse(text);});}
function normalizeTrack(track){track=track||{};return{language:track.language||'',url:track.url||'',label:track.label||null,mimeType:track.mimeType||null};}
function normalizeAsset(asset){if(!asset)return null;var a={videoUrl:asset.videoUrl||null,masterPlaylistUrl:asset.masterPlaylistUrl||null,durationSeconds:Number(asset.durationSeconds||0),audioLanguages:Array.isArray(asset.audioLanguages)?asset.audioLanguages:[],subtitleLanguages:Array.isArray(asset.subtitleLanguages)?asset.subtitleLanguages:[],externalAudioTracks:[],externalSubtitleTracks:[],videoVariants:[]},i,x;for(i=0;i<(asset.externalAudioTracks||[]).length;i++){x=normalizeTrack(asset.externalAudioTracks[i]);if(x.url)a.externalAudioTracks.push(x);}for(i=0;i<(asset.externalSubtitleTracks||[]).length;i++){x=normalizeTrack(asset.externalSubtitleTracks[i]);if(x.url)a.externalSubtitleTracks.push(x);}for(i=0;i<(asset.videoVariants||[]).length;i++){x=asset.videoVariants[i]||{};if(!x.url)continue;a.videoVariants.push({label:x.label||(x.height?x.height+'p':'Kalite'),height:Number(x.height||0),width:x.width!=null?Number(x.width):null,url:x.url,source:!!x.source});}a.videoVariants.sort(function(p,q){return Number(q.height||0)-Number(p.height||0);});return a;}
function normalizeTitle(raw){var t=raw||{},s,e;t.genres=Array.isArray(t.genres)?t.genres:[];t.posterUrls=Array.isArray(t.posterUrls)?t.posterUrls:[];t.backdropUrls=Array.isArray(t.backdropUrls)?t.backdropUrls:[];t.cast=Array.isArray(t.cast)?t.cast:[];t.crew=Array.isArray(t.crew)?t.crew:[];t.seasons=Array.isArray(t.seasons)?t.seasons:[];t.trailerUrl=t.trailerUrl||null;t.asset=normalizeAsset(t.asset);for(s=0;s<t.seasons.length;s++){t.seasons[s].episodes=Array.isArray(t.seasons[s].episodes)?t.seasons[s].episodes:[];for(e=0;e<t.seasons[s].episodes.length;e++)t.seasons[s].episodes[e].asset=normalizeAsset(t.seasons[s].episodes[e].asset);}return t;}
function titleIsPlayable(t){if(!t)return false;if(t.type==='movie')return t.status==='ready'&&!!(t.asset&&(t.asset.videoUrl||t.asset.masterPlaylistUrl));for(var s=0;s<(t.seasons||[]).length;s++){var eps=t.seasons[s].episodes||[];for(var e=0;e<eps.length;e++)if(eps[e].status==='ready'&&eps[e].asset&&(eps[e].asset.videoUrl||eps[e].asset.masterPlaylistUrl))return true;}return false;}
function snapshotUrl(){return RAW+'catalog/index.json?_='+Date.now();}
function loadSnapshot(){return xhrJson(snapshotUrl()).then(function(snap){if(!snap||!Array.isArray(snap.titles))throw new Error('catalog/index.json geçersiz.');var titles=[];for(var i=0;i<snap.titles.length;i++){var t=normalizeTitle(snap.titles[i]);if(titleIsPlayable(t))titles.push(t);}return{revision:String(snap.revision||''),generatedAt:snap.generatedAt||'',titles:titles};});}
function getTitle(id){return xhrJson(RAW+'catalog/titles/'+encodeURIComponent(id)+'.json?_='+Date.now()).then(normalizeTitle);}
function loadTitles(){return loadSnapshot().then(function(s){return s.titles;});}
function loadHome(){return xhrJson(RAW+'catalog/home.json?_='+Date.now()).then(function(home){home=home||{};home.heroTitleIds=Array.isArray(home.heroTitleIds)?home.heroTitleIds:[];home.shelves=Array.isArray(home.shelves)?home.shelves:[];return home;}).catch(function(){return{heroTitleIds:[],shelves:[],updatedAt:''};});}
function loadRevision(){return xhrJson(RAW+'catalog/version.json?_='+Date.now()).then(function(d){return d&&d.revision?String(d.revision):'';}).catch(function(){return'';});}
function artworkPool(title,kind){var primary=kind==='poster'?title.posterUrl:title.backdropUrl,extras=kind==='poster'?title.posterUrls:title.backdropUrls,out=[],seen={},i,v;if(primary)out.push(primary);extras=Array.isArray(extras)?extras:[];for(i=0;i<extras.length;i++)out.push(extras[i]);var clean=[];for(i=0;i<out.length;i++){v=String(out[i]||'').replace(/^\s+|\s+$/g,'');if(v&&!seen[v]){seen[v]=1;clean.push(v);}}return clean;}
function chooseArtwork(title,kind,seed){if(!title)return'';var pool=artworkPool(title,kind);if(!pool.length)return'';var hash=Number(seed||0)>>>0,text=String(title.id||'')+':'+kind;for(var i=0;i<text.length;i++)hash=((hash*31)+text.charCodeAt(i))>>>0;return pool[hash%pool.length];}
function lower(value){value=String(value||'');try{value=value.toLocaleLowerCase('tr-TR');}catch(e){value=value.toLowerCase();}return value.replace(/ı/g,'i').replace(/İ/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c');}
function searchTitles(titles,query){var q=lower(query).replace(/^\s+|\s+$/g,'');if(!q)return titles.slice();var result=[];for(var i=0;i<titles.length;i++){var t=titles[i],parts=[t.title,t.originalTitle,(t.genres||[]).join(' ')],j;for(j=0;j<Math.min((t.cast||[]).length,10);j++)parts.push(t.cast[j].name);if(lower(parts.join(' ')).indexOf(q)>=0)result.push(t);}return result;}
function groupByGenre(titles){var order=[],map={},i,j,gs,gname;for(i=0;i<titles.length;i++){gs=titles[i].genres&&titles[i].genres.length?titles[i].genres:['Diğer'];for(j=0;j<gs.length;j++){gname=gs[j]||'Diğer';if(!map[gname]){map[gname]=[];order.push(gname);}map[gname].push(titles[i]);}}var out=[];for(i=0;i<order.length;i++)out.push({genre:order[i],titles:map[order[i]]});return out;}
g.Film2Catalog={repo:REPO,branch:BRANCH,rawBase:RAW,loadSnapshot:loadSnapshot,loadTitles:loadTitles,loadHome:loadHome,loadRevision:loadRevision,getTitle:getTitle,normalizeAsset:normalizeAsset,normalizeTitle:normalizeTitle,titleIsPlayable:titleIsPlayable,chooseArtwork:chooseArtwork,artworkPool:artworkPool,searchTitles:searchTitles,groupByGenre:groupByGenre,xhrText:xhrText,readText:readText};
}(window));
