(function(g){'use strict';
var KEY='film2.tv.offline.v1';
function parse(raw,f){try{return JSON.parse(raw);}catch(e){return f;}}
function read(){try{var s=parse(localStorage.getItem(KEY),null);return s&&s.records?s:{records:{}};}catch(e){return{records:{}};}}
function write(st){try{localStorage.setItem(KEY,JSON.stringify(st));}catch(e){}try{var ev;try{ev=new CustomEvent('film2:offline');}catch(x){ev=document.createEvent('Event');ev.initEvent('film2:offline',true,true);}g.dispatchEvent(ev);}catch(e2){}}
function key(m){return Film2Store.mediaKey(m);}function safe(v){return String(v||'media').toLowerCase().replace(/[^a-z0-9._-]+/g,'_').replace(/^_+|_+$/g,'').slice(0,80)||'media';}
function ext(url,f){var c=String(url||'').split('?')[0],p=c.lastIndexOf('.'),v=p>=0?c.slice(p+1).toLowerCase():'';return/^[a-z0-9]{2,5}$/.test(v)?v:f;}
function supported(){try{return!!(g.tizen&&tizen.download&&tizen.systeminfo&&tizen.systeminfo.getCapability('http://tizen.org/feature/download'));}catch(e){return false;}}
function filePath(path){return String(path||'').replace(/^file:\/\//i,'');}
function record(m){return read().records[key(m)]||null;}
function selectedVideo(asset,label){var v=(asset&&asset.videoVariants)||[],i;if(label)for(i=0;i<v.length;i++)if(v[i].label===label&&v[i].url)return v[i];if(v.length){var best=v.slice().sort(function(a,b){return Number(b.height||0)-Number(a.height||0);})[0];if(best&&best.url)return best;}return asset&&asset.videoUrl?{label:'Kaynak',height:0,url:asset.videoUrl}:null;}
function updateJob(mediaKey,jobId,patch){var st=read(),rec=st.records[mediaKey];if(!rec)return;for(var i=0;i<rec.jobs.length;i++)if(Number(rec.jobs[i].id)===Number(jobId))for(var k in patch)if(Object.prototype.hasOwnProperty.call(patch,k))rec.jobs[i][k]=patch[k];var failed=false,complete=true,received=0,total=0;for(i=0;i<rec.jobs.length;i++){var j=rec.jobs[i];if(j.status==='failed'||j.status==='canceled')failed=true;if(j.status!=='complete')complete=false;received+=Number(j.received||0);if(Number(j.total||0)>0)total+=Number(j.total||0);}rec.received=received;rec.total=total;rec.updatedAt=Date.now();rec.status=failed?'failed':(complete&&rec.jobs.length?'complete':'downloading');st.records[mediaKey]=rec;write(st);}
function listener(mediaKey){return{onprogress:function(id,r,t){updateJob(mediaKey,id,{status:'downloading',received:Number(r||0),total:Number(t||0)});},onpaused:function(id){updateJob(mediaKey,id,{status:'paused'});},oncanceled:function(id){updateJob(mediaKey,id,{status:'canceled'});},oncompleted:function(id,path){updateJob(mediaKey,id,{status:'complete',fullPath:path||''});},onfailed:function(id,error){updateJob(mediaKey,id,{status:'failed',error:error&&error.message?error.message:String(error||'İndirme hatası')});}};}
function startJob(mediaKey,role,url,fileName,language,label,mimeType){var req=new tizen.DownloadRequest(url,'downloads',fileName,'ALL',{'User-Agent':'Film2TV/1.1 Samsung-Tizen'}),id=tizen.download.start(req,listener(mediaKey));if(id<0)throw new Error('İndirme başlatılamadı.');try{tizen.download.setListener(id,listener(mediaKey));}catch(e){}return{id:id,role:role,remoteUrl:url,fileName:fileName,language:language||'',label:label||'',mimeType:mimeType||'',status:'queued',received:0,total:0,fullPath:''};}
function remove(m){var st=read(),mk=key(m),rec=st.records[mk];if(!rec)return;for(var i=0;i<rec.jobs.length;i++){var j=rec.jobs[i];if(j.status!=='complete')try{tizen.download.cancel(j.id);}catch(e){}if(j.fullPath)deletePath(j.fullPath);}delete st.records[mk];write(st);}
function enqueue(m,preferred){if(!supported())throw new Error('Bu Samsung TV Download API desteklemiyor.');if(!m||!m.asset)throw new Error('Medya bulunamadı.');var existing=record(m);if(existing&&existing.status!=='failed')return existing;if(existing)remove(m);var video=selectedVideo(m.asset,preferred);if(!video||!/^https?:\/\//i.test(video.url||''))throw new Error('Çevrimdışı indirme yalnızca doğrudan MP4/progressive medya için kullanılabilir.');var mk=key(m),prefix='film2_'+safe(mk)+'_',jobs=[],st=read();st.records[mk]={key:mk,titleId:m.titleId,season:m.season,episode:m.episode,displayName:m.title+(m.subtitle?' • '+m.subtitle:''),status:'queued',qualityLabel:video.label||preferred||'',received:0,total:0,jobs:[],updatedAt:Date.now()};write(st);try{jobs.push(startJob(mk,'video',video.url,prefix+'video.'+ext(video.url,'mp4'),'','Video','video/mp4'));var subs=m.asset.externalSubtitleTracks||[];for(var i=0;i<subs.length;i++){if(!/^https?:\/\//i.test(subs[i].url||''))continue;jobs.push(startJob(mk,'subtitle',subs[i].url,prefix+'sub_'+safe(subs[i].language||i)+'.'+ext(subs[i].url,/srt/i.test(subs[i].mimeType||'')?'srt':'vtt'),subs[i].language,subs[i].label,subs[i].mimeType));}st=read();st.records[mk].jobs=jobs;st.records[mk].status='downloading';write(st);return st.records[mk];}catch(error){st=read();if(st.records[mk]){st.records[mk].jobs=jobs;st.records[mk].status='failed';st.records[mk].error=error.message||String(error);write(st);}throw error;}}
function localAsset(m,remote){var rec=record(m);if(!rec||rec.status!=='complete')return null;var video='',subs=[];for(var i=0;i<rec.jobs.length;i++){var j=rec.jobs[i];if(j.role==='video'&&j.fullPath)video=filePath(j.fullPath);if(j.role==='subtitle'&&j.fullPath)subs.push({language:j.language,label:j.label,mimeType:j.mimeType,url:filePath(j.fullPath)});}if(!video)return null;var out={};for(var k in remote)if(Object.prototype.hasOwnProperty.call(remote,k))out[k]=remote[k];out.videoUrl=video;out.masterPlaylistUrl=null;out.videoVariants=[];out.externalSubtitleTracks=subs;return out;}
function deletePath(path){if(!path||!g.tizen||!tizen.filesystem)return;var n=String(path).replace(/^file:\/\//,'');try{if(tizen.filesystem.deleteFile){tizen.filesystem.deleteFile(n,function(){},function(){});return;}}catch(e){}try{tizen.filesystem.resolve('downloads',function(dir){try{var name=n.split('/').pop(),file=dir.resolve(name);if(file&&file.fullPath)dir.deleteFile(file.fullPath,function(){},function(){});}catch(x){}},function(){},'rw');}catch(e2){}}
function rehydrate(){if(!supported())return;var st=read(),k,i,rec,j;for(k in st.records){if(!Object.prototype.hasOwnProperty.call(st.records,k))continue;rec=st.records[k];if(rec.status==='complete'||rec.status==='failed')continue;for(i=0;i<rec.jobs.length;i++){j=rec.jobs[i];if(j.status==='complete')continue;try{tizen.download.setListener(j.id,listener(k));}catch(e){try{var state=tizen.download.getState(j.id);if(state==='COMPLETED')updateJob(k,j.id,{status:'complete'});else if(state==='FAILED'||state==='CANCELED')updateJob(k,j.id,{status:'failed'});}catch(e2){}}}}}
function progress(m){var r=record(m);if(!r)return null;return{status:r.status,received:Number(r.received||0),total:Number(r.total||0),fraction:r.total>0?Math.min(1,r.received/r.total):(r.status==='complete'?1:0),qualityLabel:r.qualityLabel||'',error:r.error||''};}
g.Film2Offline={supported:supported,read:read,record:record,progress:progress,enqueue:enqueue,remove:remove,localAsset:localAsset,rehydrate:rehydrate};
}(window));
