(function (g) {
'use strict';
function j(s){try{return JSON.parse(s||'{}');}catch(e){return {};}}
function lang(c){var k=String(c||'').toLowerCase(),m={tr:'Türkçe',tur:'Türkçe',en:'İngilizce',eng:'İngilizce',de:'Almanca',deu:'Almanca',ger:'Almanca',fr:'Fransızca',fra:'Fransızca',es:'İspanyolca',spa:'İspanyolca',it:'İtalyanca',ita:'İtalyanca',ja:'Japonca',jpn:'Japonca',ko:'Korece',kor:'Korece',ar:'Arapça',ara:'Arapça',ru:'Rusça',rus:'Rusça'};return m[k]||(k?k.toUpperCase():'Bilinmeyen');}
function fmt(ms){var t=Math.max(0,Math.floor((ms||0)/1000)),h=Math.floor(t/3600),m=Math.floor((t%3600)/60),s=t%60,p=function(n){return n<10?'0'+n:String(n);};return h?h+':'+p(m)+':'+p(s):p(m)+':'+p(s);}
function ts(s){var a=String(s||'').trim().replace(',','.').split(':');return a.length===3?+a[0]*3600+(+a[1])*60+(+a[2]):a.length===2?(+a[0])*60+(+a[1]):(+a[0]||0);}
function clean(s){return String(s||'').replace(/<br\s*\/?>/gi,'\n').replace(/<[^>]+>/g,'').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>');}
function vtt(text){var b=String(text||'').replace(/^\uFEFF/,'').replace(/\r/g,'').split(/\n\n+/),o=[];for(var i=0;i<b.length;i++){var l=b[i].split('\n'),x=-1;if(!l.length||/^WEBVTT/i.test(l[0])||/^NOTE/i.test(l[0]))continue;for(var k=0;k<l.length;k++)if(l[k].indexOf('-->')>-1){x=k;break;}if(x<0)continue;var p=l[x].split('-->'),a=ts(p[0]),z=ts(String(p[1]||'').trim().split(/\s+/)[0]),q=clean(l.slice(x+1).join('\n')).trim();if(z>a&&q)o.push({start:a,end:z,text:q});}return o;}
function cue(a,t){var l=0,r=a.length-1;while(l<=r){var m=(l+r)>>1,c=a[m];if(t<c.start)r=m-1;else if(t>=c.end)l=m+1;else return c;}return null;}
function Player(cb){this.cb=cb||{};this.media=null;this.asset=null;this.url='';this.now=0;this.duration=0;this.playing=false;this.audio=[];this.text=[];this.selAudio=null;this.selSub={type:'off'};this.subCues=[];this.side=document.getElementById('sidecar-audio');this.subTimer=null;}
Player.prototype.emit=function(n){var f=this.cb[n];if(f)f.apply(null,Array.prototype.slice.call(arguments,1));};
Player.prototype.ok=function(){return !!(g.webapis&&g.webapis.avplay);};
Player.prototype.state=function(){try{return webapis.avplay.getState();}catch(e){return 'NONE';}};
Player.prototype.close=function(){try{this.side.pause();this.side.removeAttribute('src');this.side.load();}catch(e){}try{if(this.ok()&&this.state()!=='NONE')webapis.avplay.close();}catch(e2){}this.playing=false;this.subCues=[];this.emit('subtitle','');};
Player.prototype.open=function(media,opt){opt=opt||{};this.close();this.media=media;this.asset=media.asset||{};this.url=opt.url||this.asset.videoUrl||this.asset.masterPlaylistUrl||'';this.now=0;this.duration=Number(this.asset.durationSeconds||0)*1000;this.selAudio=opt.audio||this.selAudio;this.selSub=opt.sub||this.selSub||{type:'off'};var start=Number(opt.start||0),auto=opt.autoplay!==false,self=this;if(!this.ok()){this.emit('error','Samsung AVPlay API bulunamadı. Gerçek Samsung Tizen TV/TV Emulator kullanın.');return;}if(!this.url){this.emit('error','Video URL’si yok.');return;}try{webapis.avplay.open(this.url);webapis.avplay.setListener({onbufferingstart:function(){self.pauseSide();self.emit('buffer',true,0);},onbufferingprogress:function(p){self.emit('buffer',true,+p||0);},onbufferingcomplete:function(){self.emit('buffer',false,100);self.syncSide(true);},oncurrentplaytime:function(t){self.now=+t||0;if(!self.duration)try{self.duration=+webapis.avplay.getDuration()||0;}catch(e){}self.updateSub();self.syncSide(false);self.emit('time',self.now,self.duration);},onstreamcompleted:function(){self.playing=false;self.pauseSide();self.emit('completed');},onerror:function(c){self.emit('buffer',false,0);self.emit('error','AVPlay: '+c);},onerrormsg:function(c,m){self.emit('error','AVPlay: '+c+(m?' — '+m:''));},onevent:function(){},onsubtitlechange:function(d,t){if(self.selSub&&self.selSub.type==='internal'){self.emit('subtitle',clean(t));if(self.subTimer)clearTimeout(self.subTimer);self.subTimer=setTimeout(function(){if(self.selSub&&self.selSub.type==='internal')self.emit('subtitle','');},Math.max(250,+d||0));}}});webapis.avplay.setDisplayRect(0,0,1920,1080);try{webapis.avplay.setDisplayMethod('PLAYER_DISPLAY_MODE_AUTO_ASPECT_RATIO');}catch(e1){}try{webapis.avplay.setSilentSubtitle(true);}catch(e2){}webapis.avplay.prepareAsync(function(){try{self.duration=+webapis.avplay.getDuration()||self.duration;}catch(e){}self.scan();var go=function(){try{webapis.avplay.play();self.playing=true;if(!auto){webapis.avplay.pause();self.playing=false;}setTimeout(function(){self.apply();},120);self.emit('state',self.playing?'playing':'paused');}catch(x){self.emit('error','Oynatma başlatılamadı: '+x.message);}};if(start>0)try{webapis.avplay.seekTo(start,go,go);}catch(e3){go();}else go();},function(e){self.emit('buffer',false,0);self.emit('error','Video hazırlanamadı: '+(e&&e.message?e.message:e));});}catch(ex){this.emit('error','Oynatıcı açılamadı: '+(ex.message||ex));}};
Player.prototype.scan=function(){this.audio=[];this.text=[];var a=[];try{a=webapis.avplay.getTotalTrackInfo()||[];}catch(e){}for(var i=0;i<a.length;i++){var x=j(a[i].extra_info),c={index:+a[i].index,type:a[i].type,language:x.track_lang||x.language||'',codec:x.fourCC||x.codec||''};c.label=lang(c.language);if(c.type==='AUDIO')this.audio.push(c);if(c.type==='TEXT')this.text.push(c);}this.emit('tracks',this.options());};
Player.prototype.options=function(){var A=[],S=[{type:'off',label:'Kapalı',id:'off'}],i,x,e=(this.asset&&this.asset.externalAudioTracks)||[],u=(this.asset&&this.asset.externalSubtitleTracks)||[];for(i=0;i<this.audio.length;i++){x=this.audio[i];A.push({type:'internal',index:x.index,language:x.language,label:x.label,meta:x.codec||'Gömülü ses'});}for(i=0;i<e.length;i++){x=e[i];A.push({type:'external',url:x.url,language:x.language||'',label:x.label||lang(x.language),meta:'Harici ses'});}for(i=0;i<this.text.length;i++){x=this.text[i];S.push({type:'internal',index:x.index,language:x.language,label:x.label,meta:'Gömülü altyazı'});}for(i=0;i<u.length;i++){x=u[i];S.push({type:'external',url:x.url,language:x.language||'',label:x.label||lang(x.language),meta:'WebVTT altyazı'});}return {audio:A,subtitles:S};};
Player.prototype.remap=function(s,kind){if(!s||!s.language)return s;var a=kind==='audio'?this.options().audio:this.options().subtitles;for(var i=0;i<a.length;i++)if(a[i].type===s.type&&String(a[i].language||'').toLowerCase()===String(s.language).toLowerCase())return a[i];return s;};
Player.prototype.apply=function(){if(this.selAudio)this.selectAudio(this.remap(this.selAudio,'audio'),true);if(this.selSub)this.selectSub(this.remap(this.selSub,'sub'),true);};
Player.prototype.toggle=function(){try{if(this.state()==='PLAYING'){webapis.avplay.pause();this.playing=false;this.pauseSide();}else{webapis.avplay.play();this.playing=true;this.playSide();}this.emit('state',this.playing?'playing':'paused');}catch(e){this.emit('error','Oynatma değiştirilemedi: '+e.message);}};
Player.prototype.seek=function(ms){var self=this,t=Math.max(0,Math.min(+ms||0,Math.max(0,this.duration-500)));try{webapis.avplay.seekTo(t,function(){self.now=t;self.seekSide(t);self.updateSub();self.emit('time',self.now,self.duration);},function(){self.emit('error','İleri/geri sarma başarısız.');});}catch(e){self.emit('error','İleri/geri sarma başarısız.');}};
Player.prototype.seekBy=function(d){this.seek(this.now+(+d||0));};
Player.prototype.selectAudio=function(s,silent){if(!s)return;this.selAudio=s;if(s.type==='external'){try{webapis.avplay.disableAudioStream();}catch(e){}this.side.src=s.url;this.side.load();this.seekSide(this.now);if(this.playing)this.playSide();}else{try{this.side.pause();this.side.removeAttribute('src');this.side.load();}catch(e2){}try{webapis.avplay.enableAudioStream();}catch(e3){}if(s.type==='internal')try{webapis.avplay.setSelectTrack('AUDIO',+s.index);}catch(e4){if(!silent)this.emit('error','Ses değiştirilemedi.');}}if(!silent)this.emit('tracks',this.options());};
Player.prototype.selectSub=function(s,silent){s=s||{type:'off'};this.selSub=s;this.subCues=[];this.emit('subtitle','');if(s.type==='off')return;if(s.type==='internal'){try{webapis.avplay.setSilentSubtitle(true);webapis.avplay.setSelectTrack('TEXT',+s.index);}catch(e){if(!silent)this.emit('error','Altyazı değiştirilemedi.');}return;}if(s.type==='external'&&s.url){var self=this;Film2Catalog.xhrText(s.url).then(function(t){if(self.selSub&&self.selSub.url===s.url){self.subCues=vtt(t);self.updateSub();if(!self.subCues.length&&!silent)self.emit('error','WebVTT cue bulunamadı.');}}).catch(function(e){if(!silent)self.emit('error','Altyazı indirilemedi: '+e.message);});}};
Player.prototype.updateSub=function(){if(!this.selSub||this.selSub.type!=='external')return;var c=cue(this.subCues,this.now/1000);this.emit('subtitle',c?c.text:'');};
Player.prototype.seekSide=function(ms){if(this.selAudio&&this.selAudio.type==='external')try{this.side.currentTime=Math.max(0,ms/1000);}catch(e){}};
Player.prototype.syncSide=function(force){if(!this.selAudio||this.selAudio.type!=='external'||this.side.readyState<1)return;var t=this.now/1000;if(force||Math.abs((this.side.currentTime||0)-t)>.35)try{this.side.currentTime=t;}catch(e){}if(this.playing&&this.side.paused)this.playSide();};
Player.prototype.playSide=function(){if(this.selAudio&&this.selAudio.type==='external')try{var p=this.side.play();if(p&&p.catch)p.catch(function(){});}catch(e){}};
Player.prototype.pauseSide=function(){try{this.side.pause();}catch(e){}};
Player.prototype.changeSource=function(url){if(!url||url===this.url)return;this.open(this.media,{url:url,start:this.now,autoplay:this.playing,audio:this.selAudio,sub:this.selSub});};
Player.prototype.suspend=function(){this.pauseSide();try{var s=this.state();if(s==='PLAYING'||s==='PAUSED'||s==='READY')webapis.avplay.suspend();}catch(e){}};
Player.prototype.restore=function(){var self=this;try{webapis.avplay.restore(this.url,this.now,true);setTimeout(function(){self.scan();self.apply();if(self.playing)try{webapis.avplay.play();}catch(e){}self.syncSide(true);},250);}catch(e){this.open(this.media,{url:this.url,start:this.now,autoplay:this.playing,audio:this.selAudio,sub:this.selSub});}};
Player.prototype.destroy=function(){this.close();this.media=null;this.asset=null;this.now=0;this.duration=0;this.audio=[];this.text=[];};
Player.formatTime=fmt;Player.languageName=lang;Player.parseVtt=vtt;g.Film2TVPlayer=Player;
}(window));
